server:
  port: 8081

gg:
  jte:
    templateLocation: src/main/resources/jte
    developmentMode: true

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  application:
    name: mentee-power-crm

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: when-authorized


logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

