server:
  port: 8081

gg:
  jte:
    templateLocation: src/main/resources/jte
    developmentMode: true

spring:

  application:
    name: mentee-power-crm

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: when-authorized


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

