server:
  port: 8081

gg:
  jte:
    templateLocation: src/main/resources/jte
    developmentMode: true


spring:
  application:
    name: m-crm

  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
